server:
  port: 8886
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      #动态路由功能
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
      - id: EUREKA-CONSUMER
        #lb表示从注册中心获取
        uri: lb://EUREKA-CONSUMER
        predicates:
        - Query=foo
        filters:
        - AddRequestHeader=X-Request-Foo, Bar
      - id: eureka-client
        uri: lb://EUREKA-CLIENT
        predicates:
        - Path=//eureka-client/**
        - Method=Get
        filters:
        - AddRequestHeader=X-Request-Foo, eureka-client
        - StripPrefix=1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.137.1:8888/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#端点暴露
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

